export const menuNameRules = {
  bannedWords: ['스타일'],
  replacements: [
    { from: '순대국밥 스타일 국물', to: '순대국밥' },
    { from: '순대국밥 스타일', to: '순대국밥' },
    { from: '순대국밥 국물', to: '순대국밥' },
    { from: '닭개장 스타일 국물', to: '닭개장' },
    { from: '닭개장 스타일 국', to: '닭개장' },
    { from: '참치비빔밥 스타일', to: '참치비빔밥' },
    { from: '국물', to: '국' },
    { from: '브로콜리마늘볶음', to: '브로콜리 마늘볶음' },
    { from: '양상추참치비빔밥', to: '양상추 참치비빔밥' },
    { from: '참나물두부무침', to: '참나물 두부무침' },
    { from: '오징어브로콜리초무침', to: '오징어 브로콜리 초무침' },
    { from: '양상추비트샐러드', to: '양상추 비트샐러드' },
    { from: '돈육고추장짜글이', to: '돈육 고추장짜글이' },
    { from: '고구마닭갈비', to: '고구마 닭갈비' },
    { from: '황태콩나물국', to: '황태 콩나물국' },
    { from: '순두부김칫국', to: '순두부 김칫국' },
    { from: '등갈비채소볶음밥', to: '등갈비 채소볶음밥' },
    { from: '김가루쪽파무침', to: '김가루 쪽파무침' },
    { from: '매운분모자돼지볶음', to: '매운 분모자 돼지볶음' },
    { from: '닭갈비볶음밥', to: '닭갈비 볶음밥' },
    { from: '돼지고기깻잎볶음', to: '돼지고기 깻잎볶음' },
    { from: '모듬버섯초무침', to: '모듬버섯 초무침' },
    { from: '소고기두부조림', to: '소고기 두부조림' },
    { from: '양상추오리엔탈샐러드', to: '양상추 오리엔탈샐러드' },
    { from: '청경채나물무침', to: '청경채 나물무침' },
    { from: '떡갈비채소볶음', to: '떡갈비 채소볶음' },
    { from: '단무지오이무침', to: '단무지 오이무침' },
    { from: '무쌈샐러드', to: '무쌈 샐러드' },
    { from: '샐러드비빔밥', to: '양상추 참치비빔밥' },
    { from: '콩나물부추무침', to: '콩나물 부추무침' },
    { from: '사각어묵볶음', to: '사각어묵 볶음' },
    { from: '백순대채소볶음', to: '백순대 채소볶음' },
    { from: '콩비지김치비빔밥', to: '콩비지 김치비빔밥' },
    { from: '도토리묵무침', to: '도토리묵 무침' },
    { from: '양배추사과샐러드', to: '양배추 사과샐러드' },
    { from: '브로콜리두부무침', to: '브로콜리 두부무침' },
    { from: '돼지갈비덮밥', to: '돼지갈비 덮밥' },
    { from: '등갈비바베큐조림', to: '등갈비 바베큐조림' },
    { from: '고사리나물볶음', to: '고사리 나물볶음' },
    { from: '콘치즈구이', to: '콘치즈 구이' },
    { from: '망고그린샐러드', to: '망고 그린샐러드' },
    { from: '열무된장무침', to: '열무 된장무침' },
    { from: '순살조기구이', to: '순살 조기구이' },
    { from: '고등어오븐구이', to: '고등어 오븐구이' },
  ],
};

export const mealPlanningRules = {
  maxCookingTimeMinutes: 60,

  soupRules: {
    keywords: ['국', '찌개', '탕', '전골'],
    canRepeatConsecutively: true,
    maxConsecutiveDays: 2,
    preferConsecutivePlacement: true,
    preferredPatterns: ['day1-day2', 'day2-day3'],
  },

  repetitionRules: {
    avoidSameMainDishInSameWeek: true,
    avoidSameMainDishInSameMonth: true,
    allowSameSoupForTwoDays: true,
  },
};
